### ISSUE TITLE
why is meta RESOURCE vo mapping included in Results RESOURCE ?

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/ModelInstanceInVot#101]
%(FB: I don't understand why we want this "meta" RESOURCE included in a "Results" RESOURCE. Isn't that better to have this meta RESOURCE containing VODML outside any "results" RESOURCE ? (so potentially valid for all ? )

**Comment by lmichel** [comment]
The rationale is to limit the scope of the mapping to the content of one resource.
- Resources such service descriptors are obviously not concerned by the mapping
- This allows to carry data blocks, not connected to each other and mapped on different DMs. There is not use-case for this pattern though.
