### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by mcdittmar** [ivoa-std/ModelInstanceInVot#126]
The architecture diagram in the current version (2022-06-02) appears to have all the IVOA standards in it...
I believe this should be trimmed down to JUST the standards directly related to the THIS standard.. 
  + MIVOT (which ivoatex should enclose in a red box as 'this model')
  + VODML, VOTable

**Comment by loumir** [comment]
architecture diagram corrected and  regenerated at PR #133

**Comment by lmichel** [comment]
fixed by #148
