### ISSUE TITLE
Model defined data types

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#15]
We skipped the datatype issue.

This features has been added in MIVOT to support `meas:Polarization`.

The accepted polarization values are modeled as a `vodml:ENUM`

- This support this MIVOT has a `DATA_TYPE` element made of an `ENUM` of `LITERALS`
- This `DATA_TYPE` can be used as `coords:PolState.cval@dmtype`

The snippet below shows how does this work:

**QUESTION**: Should we keep this feature?

```xml
<MODEL_INSTANCE name="MANGO" syntax="ModelInstanceInVot" >
	<GLOBALS>
		<DATA_TYPE dmtype="coords:PolStateEnum">
			<ENUM>
				<LITERAL dmrole="PolStateEnum.I" name="I" />
				<LITERAL dmrole="PolStateEnum.Q" name="Q" />
				<LITERAL dmrole="PolStateEnum.U" name="U" />
				<LITERAL dmrole="PolStateEnum.V" name="V" />
				<LITERAL dmrole="PolStateEnum.RR" name="RR" />
				<LITERAL dmrole="PolStateEnum.LL" name="LL" />
				<LITERAL dmrole="PolStateEnum.RL" name="RL" />
				<LITERAL dmrole="PolStateEnum.LR" name="LR" />
				<LITERAL dmrole="PolStateEnum.XX" name="XX" />
				<LITERAL dmrole="PolStateEnum.YY" name="YY" />
				<LITERAL dmrole="PolStateEnum.XY" name="XY" />
				<LITERAL dmrole="PolStateEnum.YX" name="YX" />
				<LITERAL dmrole="PolStateEnum.PF" name="PF" />
				<LITERAL dmrole="PolStateEnum.PP" name="PP" />
				<LITERAL dmrole="PolStateEnum.PA" name="PA" />
			</ENUM>
		</DATA_TYPE>
	</GLOBALS>
	<TABLE_MAPPING tableref="Results">
		<INSTANCE dmrole="mango:MangoObject.parameters"
			dmtype="mango:Parameter">
			<!-- 
                         Mango semantic block hidden
                          -->
			<INSTANCE dmrole="mango:Parameter.measure"
				dmtype="meas:Polarization">
				<INSTANCE dmrole="meas:Polarization.coord"
					dmtype="coords:PolState">
					<ATTRIBUTE dmrole="coords:PolState.cval"
						dmtype="coords:PolStateEnum" ref="@@@@@@" />
				</INSTANCE>
			</INSTANCE>
		</INSTANCE>
	</TABLE_MAPPING>
</MODEL_INSTANCE>
```

**Comment by lmichel** [comment]
We can postpone.

- Is it a matter of concern that we can no longer map polarization states ?
- Could you consider replacing this ENUM with something more standard such as a `[string]` in Coords?

**Comment by mcdittmar** [comment]
> We can postpone.
> 
> * Is it a matter of concern that we can no longer map polarization states ?
> * Could you consider replacing this ENUM with something more standard such as a `[string]` in Coords?

I wouldn't change the model.
For this case, the annotation would be handled similarly to the vocabularies.
The value is of type 'ivoa:string' and one can lookup/verify the value in the corresponding vocabulary (referenced in the model) or modeled enumeration (also defined in the model) if they really need to.

The annotation can change as usage gets more sophisticated.

**Comment by lmichel** [comment]
OK
