### ISSUE TITLE
UTypes

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/ModelInstanceInVot#150]
UTypes : We should have the best arguments to distinguish UTypes (which remain in VOTable anyway) and MIVOT approach. Three proposals/questions

1 ) "Utypes are label attached to a FIELD or PARAM that tells its role in the model structure, typically a non cyclic graph" This is not a limitation but part of the definition. I propose to move this slot a little higher in the text just after "since it does not require any specific XML elements". Can write the PR if you all agree.

2 ) "UTypes constrain single table serializations. All model elements  must be contained within the same VOtable TABLE" I don't understand this statement.  You can have utypes for the same model in several different tables ? Maybe I don't understand the intention.

3 ) "In VODML, model leaves are no longer identified by simple strings like UTypes do, but by the role they play in a given location in the model hierarchy." But utypes also give roles in the whole VO vision, they are actually used for that when they exist !!!  So I would change this to  "In VODML, model leaves role are no longer given by simple strings like UTypes, but by the local role they play  in the model hierarchy." Can write the PR if you agree

**Comment by lmichel** [comment]
General comment: 
The spec is based on the fact that VODML **is** the standard. There no longer place for arguing for or against UTypes. The purpose of the introduction is just to spot the differences to help readers already knowing UTypes. This is why there is section starting with _The UType approach could have been extended to overcome these ....._

**Comment by lmichel** [comment]
> 2 ) "UTypes constrain single table serializations. All model elements must be contained within the same VOtable TABLE" I don't understand this statement. You can have utypes for the same model in several different tables ? Maybe I don't understand the intention.

In simpler words: the scope of one UTypes is limited to the table  where it is used; you can not join tables with UTypes

**Comment by lmichel** [comment]
> 1 ) "Utypes are label attached to a FIELD or PARAM that tells its role in the model structure, typically a non cyclic graph" This is not a limitation but part of the definition. I propose to move this slot a little higher in the text just after "since it does not require any specific XML elements". Can write the PR if you all agree.

You consider this statement as a definition rather that a limitation, fair enough.
Following your idea, the sentence could be moved before _When used as FIELD attributes..._ isn't it?

**Comment by mcdittmar** [comment]
> > 1 ) "Utypes are label attached to a FIELD or PARAM that tells its role in the model structure, typically a non cyclic graph" This is not a limitation but part of the definition. I propose to move this slot a little higher in the text just after "since it does not require any specific XML elements". Can write the PR if you all agree.
> 
> You consider this statement as a definition rather that a limitation, fair enough. Following your idea, the sentence could be moved before _When used as FIELD attributes..._ isn't it?

I won't argue the point, but I will comment that all of the 'limitations' are a result of the definition..
* by definition UTypes are not intended to be parsed, which limits reusability under different contexts
* by definition UTypes are labels attached to a FIELD or PARAM that tells its role in the model structure, which does not allow the resolution of cyclical patterns in the models.
* etc.

I don't think this text is being critical of UTypes, but explaining why the annotation syntax is needed.

I'm actually not a fan of the "The UType approach could have been extended to overcome these drawbacks,".. line.  
But.. 'drawbacks' is a more negative word, could use 'limitations' here as well, which I think is more neutral.
