### ISSUE TITLE
question about "MUST not" meaning

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/ModelInstanceInVot#152]
Very often we read "MUST NOT be empty". Actually we mean there is a requirement that the  attribute is not empty. But are the statements "MUST NOT be empty" and "MUST Be non-empty" equivalent ? The first statement may be ambiguous or mean "There is no requirement that the attribute is empty. In other words we may have it  empty
or have it non empty." Should we move everything to "MUST be non-empty" or is that unambiguous for english readers ?

**Comment by lmichel** [comment]
I propose our native speaker ( @mcdittmar ) to reply.
Using `MUST NOT` has been suggested by him AFAIK,

**Comment by mcdittmar** [comment]
My interpretation is:
    "MUST NOT be empty" means that an empty value is not allowed... so equivalent to "MUST be non-empty"

According to the referenced document for these words ([Bradner, 1997](http://www.ietf.org/rfc/rfc2119.txt)):
* MUST NOT   This phrase, or the phrase "SHALL NOT", mean that the definition is an absolute prohibition of the specification.

I certainly prefer "MUST NOT be empty" to "MUST be non-empty".

**Comment by lmichel** [comment]
Let's keep all **MUST NOT** in place

**Comment by Bonnarel** [comment]
Le 09/09/2022 à 17:58, Mark Cresitello-Dittmar a écrit :
>
> My interpretation is:
> "MUST NOT be empty" means that an empty value is not allowed... so 
> equivalent to "MUST be non-empty"
>
> According to the referenced document for these words (Bradner, 1997 
> <http://www.ietf.org/rfc/rfc2119.txt>):
>
>   * MUST NOT This phrase, or the phrase "SHALL NOT", mean that the
>     definition is an absolute prohibition of the specification.
>
> I certainly prefer "MUST NOT be empty" to "MUST be non-empty".
>
OK, thanks for the language. Let's forget my issue. I close it.
