### ISSUE TITLE
Things missing in the COLLECTION section

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/ModelInstanceInVot#153]
There is no snippet listing for COLLECTION in COLLECTION

As child of INSTANCE, the text doesn't read anything on JOIN and Collection while Table 13 does.

Table 13 doesn't read JOIN as possible element in COLLECTION embedded in GLOBALS while LIsting 10 shows that. 
If you agree I can write the PR

**Comment by lmichel** [comment]
> There is no snippet listing for COLLECTION in COLLECTION
This feature has been questioned, specially by @mcdittmar. It allows to represent multidimensional matrices.
This would be cool, but we have no real use case for this.
I propose to add an example out of the box with a 3x3 matrix

> As child of INSTANCE, the text doesn't read anything on JOIN and Collection while Table 13 does.
> Table 13 doesn't read JOIN as possible element in COLLECTION embedded in GLOBALS while LIsting 10 shows that.
> If you agree I can write the PR
I'll fix it

**Comment by mcdittmar** [comment]
> > As child of INSTANCE, the text doesn't read anything on JOIN and Collection while Table 13 does.
> > Table 13 doesn't read JOIN as possible element in COLLECTION embedded in GLOBALS while LIsting 10 shows that.
> > If you agree I can write the PR
> 
> I'll fix it


There is a difference between "embedded in GLOBALS" and "Child of GLOBALS"

The JOIN examples in Appendix C all show JOIN in COLLECTION child of INSTANCE.
The COLLECTION as child of GLOBALS is for cases such as holding a set of Frame INSTANCES which are referenced/selected from TEMPLATE instances.. these MUST have a unique ID, so cannot be generated by a JOIN.

Listing 10 is, I think, incorrect.  I can't tell.. is this the 'fix' you intend to make?

**Comment by lmichel** [comment]
There might be nothing to fix, but something to clarify.
Unit tests [allow](https://github.com/ivoa-std/ModelInstanceInVot/blob/master/schema/validation/snippets/test_9_ok.xml) JOINs in GLOBALS/COLLECTION
