### ISSUE TITLE
real life XML listing 

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#154]

**Comment by lmichel** [comment]
The goal is to make XML snippets referring to a real VO-Table. We have such a VOTable ([here](
https://github.com/ivoa/modelinstanceinvot-code/blob/package/tests/data/input/test.14.xml).

If we reformat it with less data and less text it will take 6 or 7 pages which acceptable.
I try to put label and ref in the XML with the following pattern:

```
@\label{bottom}@
@\ref{top}@
```
This works but but the this also makes the XML content to be parsed by Latex, this the `_` must be escaped or removed..

I propose to continue in that direction :
- Cleaning the XML to avoid it to pass the box bouds.
- Removing all `_` 
- Extracting snippets to replace this in the spec
- Putting labels and back references everywhere in both VOTable and snippet locations

This is big job that requires us to agree before to start.

**Comment by lmichel** [comment]
I've made a test on the MODEL section (branch `xml/snippets`) 
- add `MODEL` label just after the `\subsection` statement
- add the following comment in the XML ` <!-- @\label{MODEL_snippet}@ back to @\ref{MODEL}@ -->` This adds both a label and a hyperlink pointing back on the text.
- replace the current dummy XML snippet with this taken out from the VOTable. Do not hesitate to put `...` if too long
- Add the ref in the snippet caption: `(see in context line \ref{MODEL_snippet})` . The anchor is automatically tagged with line number within the listing.

You can test it by fetching the branch and running a `make forcetex`

**Comment by mcdittmar** [comment]
That does look like a big job, it'd be a shame to do it and have the RFC comments want to externalize it, but if you're OK with that, I think it'd be a good addition.

Comments
- do you mean remove or escape the underscores?  Many could be removed (reference ids), but there is the PRIMARY_KEY and FOREIGN_KEY elements.. not really something you can change.
- it'd be much better if we could use the actual PhotDM elements in there.
    - I've lost track of where that is in the REC process.

**Comment by lmichel** [comment]
> That does look like a big job, it'd be a shame to do it and have the RFC comments want to externalize it, but if you're OK with that, I think it'd be a good addition.

The big job is to prevent reviewers to look closely at the models used:
- dataset, Cube and Mango are just a prototypes 
- Measure, PhotDM is not sync with the REC

> FOREIGN_KEY 

We have to let `FOREIGN\_KEY`because the escape char is required but not interpreted by the parser

**Comment by lmichel** [comment]
The question is to know whether we have to continue that way.
The INTEROP is coming and the is the better period to have people getting interested in that standard
