### ISSUE TITLE
Schema Tweaks

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#18]
Templates can contains a collection
To be fixed in the diagram

**Comment by lmichel** [comment]
Do we have to keep DATATYPE?

**Comment by lmichel** [comment]
COLLECTION can have child REFERENCE

**Comment by lmichel** [comment]
For now, I made `INSTANCE@dmrole` mandatory, but I alllow it to be empty if there is a `INSTANCE@ID` which cannot be empty

**Comment by mcdittmar** [comment]
> Templates can contains a collection
> To be fixed in the diagram

I'm not entirely convinced that it should..
Trying to stay usecase driven, we have no need for this in the workshop cases (I think).

COLLECTION is used for arrays and compositions.
* compositions are from an INSTANCE, so that would not be at the TEMPLATE level
* so the only usage would be a bare array INSTANCE?

**Comment by mcdittmar** [comment]
> COLLECTION can have child REFERENCE

Yes.. I was thinking that as well.
We didn't have an example of multiple references in the workshop cases.
I'd be OK adding this without an example usage since its explicitly allowed in the VODML standard.

**Comment by mcdittmar** [comment]
> For now, I made `INSTANCE@dmrole` mandatory, but I alllow it to be empty if there is a `INSTANCE@ID` which cannot be empty

OK

**Comment by lmichel** [comment]
> TEMPLATE -> COLLECTION 

Sure, there is no usecase, let's remove it

> COLLECTION can have child REFERENCE

e.g. you map the  authors in the GLOBALS and you put them together within a dataset INSTANCE by using references

**Comment by mcdittmar** [comment]
> > COLLECTION can have child REFERENCE
> 
> e.g. you map the authors in the GLOBALS and you put them together within a dataset INSTANCE by using references

This isn't from an actual model, but yes.. something like this could occur.
