### ISSUE TITLE
Adding line numbers to XML code in Appendix A. (Complete VOTable)

### ISSUE THREAD

**Issue by rsav** [ivoa-std/ModelInstanceInVot#186]
The document contains many references to line numbers of the example XML code in Appendix A (example: _Listing 5: Example MODEL mapping block. (**see line 36** in Appendix A)_). However at least with the PDF version of the document it is not straightforward for me to locate the relevant code. 
Suggestion: add line numbers in listing

**Comment by rsav** [comment]
Ok, now I can see how to use the links and backlinks. Thanks

**Comment by lmichel** [comment]
Writing the line number wold have been a hurdle, because they would have to be updated after each XML update
