### ISSUE TITLE
Test 8.13

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#37]
Collection:  - dmrole + ATTRIBUTE + INSTANCE (mixed set) 

Typically this test maps for [12, {...}) which is legal although I've non concrete use-case for this.
The test has to be merged into OK

**Comment by mcdittmar** [comment]
My recollection is that we allow certain types of COLLECTIONs:
    * COLLECTION of ATTRIBUTE for multiplicity > 1 (attribute array)
    * COLLECTION of REFERENCE for multiplicity > 1 ( reference array)
    * COLLECTION of INSTANCEs, either direct or through JOIN
    * I don't recall when we wanted COLLECTION of COLLECTION, but it was in there somewhere.
So a COLLECTION with both ATTRIBUTE and INSTANCE elements should be illegal (and other bad combinations)

The current syntax diagram shows 2 sets
   (ATTRIBUTE|REFERENCE) || ( INSTANCE|JOIN|COLLECTION)
which is what the current test is directed toward.

**Comment by lmichel** [comment]
You are right, but taking into account that REFERENCE refers to INSTANCE, I would say that the current patterns are
 (ATTRIBUTE) || ( INSTANCE|JOIN|COLLECTION|REFERENCE) indeed

**Comment by lmichel** [comment]
Schema updated

**Comment by mcdittmar** [comment]
The schema update looks good.
But I think we will need to fine-tune the spec as we go through the workshop cases.  I disagree that REFERENCE should be included in the COLLECTION of INSTANCES, these are not mixed.

I went through the time series example we used during the earlier discussion and made up a revised description, which I put into the Test 8 OK case file:

    The COLLECTION element is used for multple purposes, each having a limited 
    subset of elements for its content. 
     1) Array attribute (multiplicity > 1).
        COLLECTION contains the array as a set of ATTRIBUTE nodes
        The dmrole of the COLLECTION is inherited by its contents.
     2) Reference relation with multiplicity > 1
        COLLECTION contains the set of REFERENCEs
        The dmrole of the COLLECTION is inherited by its contents.
     3) Composition relation with multiplicity > 1
        COLLECTION contains the set of INSTANCEs, either direct INSTANCE or through JOIN
     4) Proxy for TABLE; grouping of common INSTANCES for selection by PRIMARY/FOREIGN key.
        COLLECTION contains the set of INSTANCES to be selected from.
        COLLECTION MUST have an ID, used as the tableref in the corresponding REFERENCEs
        COLLECTION has no specified dmrole (is empty)

I'm still not sure where COLLECTION of COLLECTION comes into play.

**Comment by lmichel** [comment]
COLLECTION of COLLECTION is a pattern  one can have in a model (*), I've no concrete case for this though.
The question is is to know whether we should allow a possible feature that has no use case:
PRO: this makes the mapping more flexible
CON: waste of time for client/validator developers

*: `[[ra1, dec1], [ra2, dec2]...]`

**Comment by lmichel** [comment]
For the REFERENCE, my take is to allow simple REFERENCEs  aninstance from within a collection (case 3)
```
GLOBALS
   INSTANCE ID=xxx

TEMPLATES
   INSTANCE
    COLLECTION
       INSTANCE
       REFERENCE on ID=xxx
```

**Comment by mcdittmar** [comment]
I think I understand.. 
In that usage, the REFERENCE isn't a modeled reference, but a pointer, saying "include that Instance in this collection",  similar to the JOIN.  This has a certain logic to it, but unless we have a concrete case where this usage is really helpful, I'd rather not allow it as a starting point.  Keep REFERENCE as a modeled reference only.


> For the REFERENCE, my take is to allow simple REFERENCEs on global instances from within a collection (case 3)
> 
> ```
> GLOBALS
>    INSTANCE ID=xxx
> 
> TEMPLATES
>    INSTANCE
>     COLLECTION
>        INSTANCE
>        REFERENCE on ID=xxx
> ```

**Comment by lmichel** [comment]
In Coords: points (e.g. ra/dec) refer to a frame.
In term of very simplified modeling, you will get something like:

```
GLOBALS
   INSTANCE ID=J2000

TEMPLATES
  INSTANCE Point
    ATTRIBUTE ra
    ATTRIBUTE des
    REFERENCE Frame -> J2000
```
This is a real case, but not in a collection.
I've no similar pattern in a COLLECTION, then my only argument is to keep it is to remain symetric with the INSTANCE content.
Ok, it's a weak argument!
If you insist a very little bit, we can remove it.
