### ISSUE TITLE
Dynamic reference resolution.

### ISSUE THREAD

**Issue by mcdittmar** [ivoa-std/ModelInstanceInVot#6]
The MIIVOT syntax element GROUPBY supports the case where you want to iterate over unique column values from a VOTable, generating Instances for each iteration.

The best use case example for this scenario is the "GAIA Multiband Time Series" data.
The data is serialized as a single TABLE, containing multiple TimeSeries instances, one for each 'band' and 'source-id' in a very compact representation ( source_id, band, time, flux, etc.. ).  NOTE: the sample file contains only 1 source-id, but it is reasonable to assume there can be more than one.

I was going to expound a little here about the GROUPBY usage and syntax, but this may raise questions outside the scope of this ticket.   The focus of this ticket is some functionality which is lost (relative to the VODML/MAPPING syntax), in part, by the design of the GROUPBY element.

Issue:
* In this use case, there are instances which have references to certain metadata.
* the selection of the referred instance is dependent on the value of a column in the table (in this case, these dependencies are KEYs, in the GROUPBY iteration, but that may not always be the case, I'm not sure).
    * Photometry coordinate -> Coordinate system containing appropriate Filter information based on 'band' column value
    * DatasetMetadata -> each TimeSeries references associated Dataset metadata appropriate for the 'source_id'.

This functionality is lost in the current MIIVOT syntax compared to the VODML/MAPPING syntax.
With the VODML/MAPPING syntax, this is accomplished with applications of the PRIMARYKEY/FOREIGNKEY pairs.

1) TimeSeries association to Dataset
```
    <GLOBALS ID="_Dataset">
      <INSTANCE dmtype="ds:experiment.ObsDataset" ID="_ds1">
        <PRIMARYKEY>
          <PKFIELD>
            <LITERAL dmtype="ivoa:string" value="5813181197970338560"/>
          </PKFIELD>
        </PRIMARYKEY>
        # Dataset Metadata instance content here
      </INSTANCE>
      # One INSTANCE per source_id - PKFIELD
    </GLOBALS>

    # The TimeSeries references appropriate Dataset metadata using FOREIGNKEY.
    # matching the current value of _pksrcid to the corresponding value in the set labeled '_Dataset'.
    <TEMPLATES tableref="_PKTable">
      <INSTANCE dmtype="cube:SparseCube" ID="_TimeSeries">
        <REFERENCE dmrole="cube:DataProduct.dataset">
          <FOREIGNKEY>
            <PKFIELD>
              <COLUMN dmtype="ivoa:string" ref="_pksrcid"/>
            </PKFIELD>
            <TARGETID>_Dataset</TARGETID>
          </FOREIGNKEY>
        </REFERENCE>
       # remainder of TimeSeries instance content..
      </INSTANCE>
    </TEMPLATES>

```

2) Coordinate system (with Filter) association to Measurement coordinate.
```
    <GLOBALS ID="_CoordinateSystems">
      <INSTANCE dmtype="mango:coordinates.PhotometryCoordSys" ID="_photsys_G">
        <PRIMARYKEY>
          <PKFIELD>
            <LITERAL dmtype="ivoa:string" value="G"/>
          </PKFIELD>
        </PRIMARYKEY>
        # CoordSys content, with "G-band" Filter content
      </INSTANCE>
      <INSTANCE dmtype="mango:coordinates.PhotometryCoordSys" ID="_photsys_RP">
        <PRIMARYKEY>
          <PKFIELD>
            <LITERAL dmtype="ivoa:string" value="RP"/>
          </PKFIELD>
        </PRIMARYKEY>
        # CoordSys content, with "RP-band" Filter content
      </INSTANCE>
      # etc.. 
    </GLOBALS>

   # The photometric coordinate references a CoordSystem
   # Which Coordinate system depends on the value of the '_band" column in the current Table.
                <ATTRIBUTE dmrole="meas:GenericMeasure.coord">
                  <INSTANCE dmtype="coords:PhysicalCoordinate">
                    <ATTRIBUTE dmrole="coords:PhysicalCoordinate.cval">
                      <COLUMN dmtype="ivoa:RealQuantity" ref="_mag"/>
                    </ATTRIBUTE>
                    <REFERENCE dmrole="coords:Coordinate.coordSys">
                      <FOREIGNKEY>
                        <PKFIELD>
                          <COLUMN dmtype="ivoa:string" ref="_band"/>
                        </PKFIELD>
                        <TARGETID>_CoordinateSystems</TARGETID>
                      </FOREIGNKEY>
                    </REFERENCE>
                  </INSTANCE>
                </ATTRIBUTE>
```
NOTE: these examples have the instances in GLOBALS, I believe the same mechanism applies to Instances generated with a TEMPLATE, where the selection then chooses instance generated from the row matching the KEY criteria.

The primary criteria for this functionality seem to be:
* ID of element containing the candidate Instances
* Element containing candidate instances 
    * each instance identifies Primary Key(s) and their values, indicating when they apply.
* Column(s) from current Table used as Key(s) to be matched against candidate instances.

In the MIIVOT syntax, the counterpart to the REFERENCE node is the dmref attribute in INSTANCE. 
This serves well for a static reference, but there is no hook to allow for this dynamic reference resolution.

**Comment by lmichel** [comment]
The example given above is not related to the GROUPBY feature which does not exist as such in VM, does it?
It relates to the possibility of joining table data with static data GLOBALS, is that true?

**Comment by lmichel** [comment]
I'm a little puzzled  with joining data with GLOBALS items because the content of GLOBALS is anything but an homogeneous data collection as table are..

**Comment by mcdittmar** [comment]
> I'm a little puzzled with joining data with GLOBALS items because the content of GLOBALS is anything but an homogeneous data collection as table are..

They can be.. when this functionality is needed, one can create a GLOBALS node with homogeneous content.
VM allows >1 GLOBALS node.

**Comment by lmichel** [comment]
I'm not very sure that multiple GLOBALS really helps (the parser)

I've been rewriting your example ala MIVOT:
- Filters grouped in a COLLECTION, so that we can state the REFERENCE@ref must be resolved against either a FIELD or a COLLECTION
- KEYS built with the same pattern as INSTANCEs
- REFERENCE built with the same pattern as JOIN

```xml
<GLOBALS ID="_CoordinateSystems">
	<COLLECTION dmrole="" ID="_filters">
		<INSTANCE dmtype="mango:coordinates.PhotometryCoordSys" ID="_photsys_G">
			<PRIMARYKEY dmtype="ivoa:string" value="G"/>
        # CoordSys content, with "G-band" Filter content
		</INSTANCE>
		<INSTANCE dmtype="mango:coordinates.PhotometryCoordSys" ID="_photsys_RP">
			<PRIMARYKEY dmtype="ivoa:string" value="RP"/>
        # CoordSys content, with "RP-band" Filter content   
		</INSTANCE>
	</COLLECTION>
      # etc.. 
</GLOBALS>

   # The photometric coordinate references a CoordSystem
   # Which Coordinate system depends on the value of the '_band" column in the current Table.
                
<ATTRIBUTE dmrole="meas:GenericMeasure.coord">
	<INSTANCE dmtype="coords:PhysicalCoordinate">
		<ATTRIBUTE dmrole="coords:PhysicalCoordinate.cval" dmtype="ivoa:RealQuantity" ref="_mag"/>
		<REFERENCE dmrole="coords:Coordinate.coordSys" dmtype="ivoa:string" ref="_band" table_ref"_filters"/>
	</INSTANCE>
</ATTRIBUTE>
```
My concern is still to facilitate the XPath-based parsing of course.

**Comment by mcdittmar** [comment]
> The example given above is not related to the GROUPBY feature which does not exist as such in VM, does it?
> It relates to the possibility of joining table data with static data GLOBALS, is that true?

This is the issue that I was thinking of in my summary.  It is not directly related to GROUPBY, and I'm realizing this morning that my interpretation of GROUPBY may have been a bit off (thinking it defined 2 loops).  The issue does manifest during the GROUPBY usage thread.
Can I rename this issue?  Maybe just "Column value dependent references"

**Comment by lmichel** [comment]
Yes, withe the word "dynamic reference resolution"

You can also add a row in the Wiki table

**Comment by mcdittmar** [comment]
> I'm not very sure that multiple GLOBALS really helps (the parser)
> 
> I've been rewriting your example ala MIVOT:
> 
> * Filters grouped in a COLLECTION, so that we can state the REFERENCE@ref must be resolved against either a FIELD or a COLLECTION

The COLLECTION in GLOBALS would allow you to retain 1 GLOBALS node, but still group the content where needed.. OK

> * KEYS built with the same pattern as INSTANCEs
PRIMARYKEY within INSTANCE.. OK

> * REFERENCE built with the same pattern as JOIN
ref = foreign key?  match the VOTable '_band' element value with those in at table_ref.
table_ref = since this isn't always a table, maybe a different name? "container"?

The element being referenced here is an INSTANCE, so what happens with the dmref attribute in  INSTANCE?
Does it move to this REFERENCE node?

**Comment by mcdittmar** [comment]
To work through the issues more effectively (I hope), I've taken my annotated Gaia multi band file, and hand-converted it to using the 'merged' syntax from the workshop session.  I then folded in the elements being discussed here, to resolve this issue.  The idea is to start from a syntax we know works (the VM example) and migrate from there.. hopefully will help avoid loosing functionality.

[Sandbox annotation](https://github.com/mcdittmar/dm-usecases/blob/main/usecases/time-series/mcd-implementation/gaia_multiband_alternate.vot)

There are comments at the top of the file on what was changed, and why.
From the above suggestions I hit the following problems:
1) REFERENCE as noted above would allow only 1 key to resolve the match
2) With PRIMARYKEY introduced; replaced generic KEY spec with PRIMARYKEY|FOREIGNKEY 

With this, I believe I have annotated the example in a way that resolves this issue.
Of course, with no code to interpret/consume it, this is not testable at this point.

The changes to the 'merged' syntax spec are:
```
  - KEY dropped in favor of individual PRIMARYKEY/FOREIGNKEY elements
  + PRIMARYKEY( @dmtype=<vodmlid> @ref=<votable_element> @value=<literal> )
  + FOREIGNKEY( @dmtype=<vodmlid> @ref=<votable_element> @value=<literal> )
  + REFERENCE( @dmref=<instance> @tableref=<container> ); @tableref utilized FOREIGNKEY within REFERENCE
  * INSTANCE drops @dmref option; references handled by REFERENCE node.
  * ATTRIBUTE now contains one of INSTANCE|COLLECTION|REFERENCE
```

Take a look, if you agree, we can move on to another issue.

**Comment by mcdittmar** [comment]
> You can also add a row in the Wiki table

The wiki page does not allow edit.

**Comment by lmichel** [comment]
You are invited as maintainer


Laurent
—
Translate with https://www.deepl.com/translator
-- 
jesuischarlie/Tunis/Paris/Bruxelles/Berlin

Laurent Michel
SSC XMM-Newton
Tél : +33 (0)3 68 85 24 37
Fax : +33 (0)3 )3 68 85 24 32
Université de Strasbourg <http://www.unistra.fr>
Observatoire Astronomique
11 Rue de l'Université
F - 67200 Strasbourg

**Comment by lmichel** [comment]
Can you provide REFERENCE examples: one with static  (ref->ID) ref and another with dynamic ref (ref -> key)?

In you _merge example_ you are using INSTANCE for both model leaves and complex objects.
I really prefer to keep them distinct and set ATTRIBUTEs as child of INSTANCE (or COLLECTION) and make those elements carrying their roles:
- If the standard states that all ATTRIBUTEs, REFERENCEs and COLLECTIONs enclosed in INSTANCEs are attributes, there is no longer reason to repeat this everywhere.
- INSTANCEs being child of something being not an INSTANCE have no role (empty or none TBD) 
- This way to proceed is even more consistent once we have said that INSTANCEs can no longer be used for references.

Instead of the this ( _merge example_ )
```xml
<INSTANCE dmtype="mango:coordinates.PhotometryCoordSys" ID="_photsys_G">
	<PRIMARYKEY dmtype="ivoa:string" value="G"/>
	<ATTRIBUTE dmrole="coords:PhysicalCoordSys.frame">
		<INSTANCE dmtype="mango:coordinates.PhotFilter">
			<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.name">
				<INSTANCE value="GAIA/GAIA2r.G" dmtype="ivoa:string"/>
			</ATTRIBUTE>
			<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.zeroPointFlux">
				<INSTANCE value="2.49524e-9" dmtype="ivoa:RealQuantity"/>
			</ATTRIBUTE>
			<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.magnitudeSystem">
				<INSTANCE value="Vega" dmtype="ivoa:string"/>
			</ATTRIBUTE>
			<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.effectiveWavelength">
				<INSTANCE value="6246.77" dmtype="ivoa:RealQuantity"/>
			</ATTRIBUTE>
			<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.unit">
				<INSTANCE value="Angstrom" dmtype="ivoa:Unit"/>
			</ATTRIBUTE>
			<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.bandWidth">
				<INSTANCE value="4578.32" dmtype="ivoa:real"/>
			</ATTRIBUTE>
		</INSTANCE>
	</ATTRIBUTE>
</INSTANCE>
```

You get this ( hand-made conversion from a _merge example_  snippet)
I'm pretty sure that any parser or annoter would appreciate.

```xml
<INSTANCE dmtype="mango:coordinates.PhotometryCoordSys" ID="_photsys_G">
	<PRIMARYKEY dmtype="ivoa:string" value="G"/>
	<INSTANCE dmrole="coords:PhysicalCoordSys.frame" dmtype="mango:coordinates.PhotFilter">
		<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.name"  value="GAIA/GAIA2r.G" dmtype="ivoa:string"/>
		<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.zeroPointFlux" value="2.49524e-9" dmtype="ivoa:RealQuantity"/>
		<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.magnitudeSystem" value="Vega" dmtype="ivoa:string"/>
		<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.effectiveWavelength" value="6246.77" dmtype="ivoa:RealQuantity"/>
		<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.unit" value="Angstrom" dmtype="ivoa:Unit"/>
		<ATTRIBUTE dmrole="mango:coordinates.PhotFilter.bandWidth" value="4578.32" dmtype="ivoa:real"/>
	</INSTANCE>
</INSTANCE>
```

**Comment by lmichel** [comment]
After having looked at the code above, I admit that the word ATTRIBUTE can be interpreted in many different  ways and this it is not the most appropriate name for the elements it is used for.
I suggest to take advantage on the proposal MCD made for the Mango parameters: PROPERTY:

```xml
<INSTANCE dmtype="mango:coordinates.PhotometryCoordSys" ID="_photsys_G">
	<PRIMARYKEY dmtype="ivoa:string" value="G"/>
	<INSTANCE dmrole="coords:PhysicalCoordSys.frame" dmtype="mango:coordinates.PhotFilter">
		<PROPERTY dmrole="mango:coordinates.PhotFilter.name"  value="GAIA/GAIA2r.G" dmtype="ivoa:string"/>
		<PROPERTY dmrole="mango:coordinates.PhotFilter.zeroPointFlux" value="2.49524e-9" dmtype="ivoa:RealQuantity"/>
		<PROPERTY dmrole="mango:coordinates.PhotFilter.magnitudeSystem" value="Vega" dmtype="ivoa:string"/>
		<PROPERTY dmrole="mango:coordinates.PhotFilter.effectiveWavelength" value="6246.77" dmtype="ivoa:RealQuantity"/>
		<PROPERTY dmrole="mango:coordinates.PhotFilter.unit" value="Angstrom" dmtype="ivoa:Unit"/>
		<PROPERTY dmrole="mango:coordinates.PhotFilter.bandWidth" value="4578.32" dmtype="ivoa:real"/>
	</INSTANCE>
</INSTANCE>
```
So that, one can say that INSTANCEs are made of nested PROPERTY, COLLECTIONs and INSTANCES (and REFERENCEs)

**Comment by mcdittmar** [comment]
> Can you provide REFERENCE examples: one with static (ref->ID) ref and another with dynamic ref (ref -> key)?

There were 2 of these in the example file which I hadn't converted to the REFERENCE node.
1) ds:experiment.ObsDataset.target
2) coords:Coordinate.coordSys on the Time measure.
I've update the example file (commit c45ac05)

RE: separation of ATTRIBUTE/INSTANCE here.
I've noted these comments in Issue #1 .  The starting point was the merged syntax, and I'm hoping to fold in the Issue resolutions one at a time, starting with this missing functionality.  The resolution of this may effect how Issue #1 is handled (which is more an efficiency issue than functionality).

**Comment by mcdittmar** [comment]
Pending verification and resolution of other issues which may effect these elements,  
the proposed changes to the "merged" annotation syntax to accommodate this functionality are:
```
  - KEY dropped in favor of individual PRIMARYKEY/FOREIGNKEY elements
  + PRIMARYKEY( @dmtype=<vodmlid> @ref=<votable_element> @value=<literal> )
  + FOREIGNKEY( @ref=<votable_element> )
  + REFERENCE( @dmref=<instance> @tableref=<container> ); @tableref utilized FOREIGNKEY within REFERENCE
  * INSTANCE drops @dmref option; references handled by REFERENCE node.
  * ATTRIBUTE now contains one of INSTANCE|COLLECTION|REFERENCE
```
