### ISSUE TITLE
Mapping PARAMS

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#90]
In element_attribute.tex
The current definition of the attribute do not allow to map PARAM
![Screenshot 2022-02-04 at 13 15 47](https://user-images.githubusercontent.com/11462648/152527521-c90e3fb6-7b5c-40a9-8e7c-1b33dd717363.png)

To be clarified and fixed if needed

**Comment by mcdittmar** [comment]
ATTRIBUTE should certainly be allowed to reference PARAM under GLOBALS.  We have lots of test cases using that.
I think the expectation is that the behavior is similar to under TEMPLATES, but cannot refer to a FIELD..
```
In this case, the ATTRIBUTE must be specified by:
 * @ref - reference to a VOTable PARAM, (not a VOTable FIELD)
 * @value - a literal
 * if both are provided; @value serves as the default if the reference cannot be resolved
```

**Comment by Bonnarel** [comment]
Fine ! So text should be fixed
