### ISSUE TITLE
The role of @vakue vs @ref must be clarified

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#91]
In element_attribute.tex

![Screenshot 2022-02-04 at 13 18 28](https://user-images.githubusercontent.com/11462648/152527859-1a22cffa-c225-48f3-9f8d-f5e1fae74013.png)

**Comment by mcdittmar** [comment]
In this case, the ATTRIBUTE must be specified by:
* \@ref - reference to a VOTable FIELD (a particular row item)
* \@value - a literal
* if both are provided, \@value serves as the default if the reference cannot be resolved

**Comment by Bonnarel** [comment]
Agreed. Anyway,  my point was only about changing "of a particular...." to "or a particular..." Correct ?
