### ISSUE TITLE
The purpose of GLOBALS/COLLECTION must be clarified

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#92]
in element_collection.text
![Screenshot 2022-02-04 at 13 21 20](https://user-images.githubusercontent.com/11462648/152528242-05e9928f-3297-4e45-815a-c01b4107306c.png)

**Comment by mcdittmar** [comment]
The use-case we used this for was:
GLOBALS contains a COLLECTION of photometry filter INSTANCEs.
TEMPLATES maps the TABLE content to Photomety points (for example),
and we need to match the 'table.band' column value to the corresponding Photometry Filter instance from the collection.

The photometry filter INSTANCEs use the PRIMARY_KEY for making the match.

So here, the VODML COLLECTION is very much serving as a proxy for a VOTable TABLE.  Had the provider generated a TABLE of Photometry Filters, that could have been used instead.  I haven't checked, but you would mostly need this approach if the provider does include the Photometry filter metadata.. as PARAMs.   If the content were all literals (no references to PARAMs), then the annotator could add a TABLE and join to that.  I'm not sure how I feel about that path, but it is an option for them.

In what ways do we need to enhance the description?  What piece is missing?

**Comment by Bonnarel** [comment]
> The use-case we used this for was: GLOBALS contains a COLLECTION of photometry filter INSTANCEs. TEMPLATES maps the TABLE content to Photomety points (for example), and we need to match the 'table.band' column value to the corresponding Photometry Filter instance from the collection.
> 
OK. Got it. I realize that there was a typo in my comment. I meant "... the same idea..." instead of "... the same IF..." which is non-understable.

> The photometry filter INSTANCEs use the PRIMARY_KEY for making the match.
> 
so "common INSTANCES for selection by included PIMARY_KE / external FOREIGN_KEY'"

> So here, the VODML COLLECTION is very much serving as a proxy for a VOTable TABLE. Had the provider generated a TABLE of Photometry Filters, that could have been used instead.

OK

 > I haven't checked, but you would mostly need this approach if the provider does include the Photometry filter metadata.. as PARAMs. 

Which approach ? The COLLECTION one or the TABLE one ?


> If the content were all literals (no references to PARAMs), 
Not sure I get it. I'm lost there
> then the annotator could add a TABLE and join to that. I'm not sure how I feel about that path, but it is an option for them.
> 
> In what ways do we need to enhance the description? What piece is missing?

Well I understand that the COLLECTION of INSTANCES is workink like a TABLE with several raws. I don't catch the PARAM comparison at the moment

**Comment by mcdittmar** [comment]
> > I haven't checked, but you would mostly need this approach if the provider does include the Photometry filter metadata.. as PARAMs.
> 
> Which approach ? The COLLECTION one or the TABLE one ?
> 
> > If the content were all literals (no references to PARAMs),
> > Not sure I get it. I'm lost there
> > then the annotator could add a TABLE and join to that. I'm not sure how I feel about that path, but it is an option for them.
> > In what ways do we need to enhance the description? What piece is missing?
> 
> Well I understand that the COLLECTION of INSTANCES is workink like a TABLE with several raws. I don't catch the PARAM comparison at the moment


Sorry to add to the confusion.
My point was simply that:
* If the data provider includes PARAMs with the photometry filter metadata, then the annotation really must be done as a COLLECTION under GLOBALS.
* If they don't, then the annotator has the choice of annotating as a COLLECTION under GLOBALS, or adding a TABLE and annotating that.

**Comment by Bonnarel** [comment]
Le 10/02/2022 à 05:42, Mark Cresitello-Dittmar a écrit :
>
>         I haven't checked, but you would mostly need this approach if
>         the provider does include the Photometry filter metadata.. as
>         PARAMs.
>
>     Which approach ? The COLLECTION one or the TABLE one ?
>
>         If the content were all literals (no references to PARAMs),
>         Not sure I get it. I'm lost there
>         then the annotator could add a TABLE and join to that. I'm not
>         sure how I feel about that path, but it is an option for them.
>         In what ways do we need to enhance the description? What piece
>         is missing?
>
>     Well I understand that the COLLECTION of INSTANCES is workink like
>     a TABLE with several raws. I don't catch the PARAM comparison at
>     the moment
>
> Sorry to add to the confusion.
> My point was simply that:
>
>   * If the data provider includes PARAMs with the photometry filter
>     metadata, then the annotation really must be done as a COLLECTION
>     under GLOBALS.
>   * If they don't, then the annotator has the choice of annotating as
>     a COLLECTION under GLOBALS, or adding a TABLE and annotating that.
>
> —
>
OK. Thanks, Mark !
