### ISSUE TITLE
The behaviour of JOIN on either GLOBALS/COLLECTION or TEMPLATES must be clarified

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#93]
in element_foreign_key.tex
![Screenshot 2022-02-04 at 13 25 02](https://user-images.githubusercontent.com/11462648/152528703-7f7e4d71-f2e0-460c-8222-384de3bc6bfc.png)

**Comment by lmichel** [comment]
Also in element_reference.tex
![Screenshot 2022-02-04 at 13 27 08](https://user-images.githubusercontent.com/11462648/152528950-1b0f8cf8-fcf4-432a-9668-35976743dabc.png)

**Comment by mcdittmar** [comment]
I can see how the name 'tableref' can be confusing if it is allowed to refer to a VODML COLLECTION as well as a VOTable TABLE.  I think the initial feeling was that these would be VOTable TABLEs, but the use-case where we store coordinate systems in a COLLECTION under GLOBALS and want to match each TEMPLATE row to one of these opened the scope.

We do need a different name (from 'ref', a reference to a VOTable field/param, and 'dmref' a reference to a VODML instance.)
Perhaps something generic like 'sourceref', reference to the source 'set of instances' to pull from.. a COLLECTION or TABLE.
would be more clear.

**Comment by Bonnarel** [comment]
OK for sourceref

**Comment by lmichel** [comment]
ok
