### ISSUE TITLE
Not using the dataset word for VOTABLE: confusing

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#96]
in use-cases.tex
![Screenshot 2022-02-04 at 13 32 30](https://user-images.githubusercontent.com/11462648/152529656-ea828109-4cf9-4e78-9c90-be4e31b1620b.png)

**Comment by mcdittmar** [comment]
The word 'datasets' here, in both cases is simply meaning 'a single annotated VOTable'.  The point of the paragraph being that the above use-cases are about mapping a single VOTable while then next case is about interoperability, and identifying/reconciling the nature of common instances from multiple annotated VOTables.

"The above cases relate to the description of instances in a single VOTable.  Model annotations become even more important in cases where interoperability is required, for example to identify and reconcile common instances from multiple VOTables."

**Comment by Bonnarel** [comment]
The new phrasing is OK for me. Thanks
The misunderstanding came than very often in VOTables, raws maybdescribe (external) datasets.
