### ISSUE TITLE
The scope of the different mapping element must be clarified before to dive into the details

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#98]
(From GL)
A new section could be added to specify high level mapping structure.
Distinction between element for
- data mapping
- data referencing
- block structure

Mapping policy: are we supposed to map all model fields?

**Comment by mcdittmar** [comment]
Can you clarify what is being requested here?  Is this to explain that INSTANCE is mapping a model element, while JOIN has nothing to do with the model, but accommodates how the provider has serialized the data.

**Comment by lmichel** [comment]
The INSTANCE/JOIN example given above is exactly what we should highlight.
I propose to add a short section telling the purpose of the different elements, something similar to what I presented in the Feb running [meeting] (https://wiki.ivoa.net/internal/IVOA/DMRunning022022/DMRunning-02-2022.pdf) .
This wouldn't provide new information, but this would give a helpful guideline for readers along with Figure 2

**Comment by lmichel** [comment]
Fixed by #106
