### ISSUE TITLE
Duplicated introduction

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/ModelInstanceInVot#99]
It turns out that the beginning of section2 (use-cases) tells the same with the instruction but with a different wording.
The most interesting parts of this paragraph must pushed up into the intro and it must then be removed .

**Comment by Bonnarel** [comment]
> It turns out that the beginning of section2 (use-cases) tells the same with the instruction but with a different wording. The most interesting parts of this paragraph must pushed up into the intro and it must then be removed .

instruction ---> introduction, I think
